# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Rscript build release

on:
  release:
    # Must republish release to update assets
    types: [ published ]

jobs:
  release-file-system-image:
    uses: r-wasm/actions/.github/workflows/release-file-system-image.yml@v1
    permissions:
      # For publishing artifact files to the release
      contents: write
      # To download GitHub Packages within action
      repository-projects: read